# Settings that affect the whole blog.  This file is *NOT* reloaded automatically when
# using `bundle exec jekyll serve` -- the server process has to be restarted.

# Site settings.  These are accessed in the HTML files via {{ site.title }},
# {{ site.email }}, and so on.  Any custom variable can be created and will be accessible
# in the templates via {{ site.myvariable }}.
title: meribold
author: Lukas Waymann
email: meribold@gmail.com
description: > # ignore newlines until `baseurl:`
  Yak shaver.
url: "https://meribold.github.io"
# twitter_username: mribld
github_username:  meribold

minima:
  # See <http://shopify.github.io/liquid/filters/date/>.
  date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# The following items will not be processed by default (can be overridden with a custom
# list).
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# vim: tw=90 sts=-1 sw=2 et
