# Settings that affect the whole blog.  This file is *NOT* reloaded automatically when
# using `bundle exec jekyll serve` -- the server process has to be restarted.

# Site settings.  These are accessed in the HTML files via {{ site.title }},
# {{ site.email }}, and so on.  Any custom variable can be created and will be accessible
# in the templates via {{ site.myvariable }}.
title: Yak Shaving
author: Lukas Waymann
email: meribold@gmail.com
# description: >
#   My personal website.  There is nothing interesting here yet.
url: "https://meribold.github.io"
github_username:  meribold
# twitter_username: mribld
# See <http://shopify.github.io/liquid/filters/date/>.
date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown

# vim: tw=90 sts=-1 sw=2 et
