# Settings that affect the whole site.  This file is *NOT* reloaded automatically when
# using `bundle exec jekyll serve` -- the server process has to be restarted.

# Site settings.  These are accessed in the HTML files via {{ site.title }},
# {{ site.email }}, and so on.  Any custom variable can be created and will be accessible
# in the templates via {{ site.my_variable }}.  Some of these are used by
# [jekyll-seo-tag][1].
#
# [1]: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
description: Personal Site
author: Lukas Waymann
email: io@meribold.org
twitter:
  username: mribld
# See <http://shopify.github.io/liquid/filters/date/>.
date_format: "%Y-%m-%d"
permalink: pretty
show_drafts: false
future: false
unpublished: false
# See <http://jekyllrb.com/docs/collections/>.
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - README.md
  - makefile
  - node_modules/
  - package.json
  - package-lock.json
  - tags
include:
  - .well-known

defaults:
  - scope:
      path: googled1df7058b163306e.html
    values:
      sitemap: false
