document.querySelector("header #epigraph").innerHTML = [
   "☕",
   "🖖",
   "💈",
   "<i>Elbereth</i>",
   "<i>E?be?eth</i>",
   "<i>I summon entropy!</i>",
   "<i>Who grew your hands?</i>",
   "<i>We've been activated!</i>",
   "<i>Curiouser and curiouser!</i>",
   "<i>Move slow and make things.</i>",
   "<i>Everything fast is slow again.</i>",
   "<i>Not all those who wander are lost.</i>",
   "<i>Everything not saved will be lost.</i>",
   "<i>What one fool can do, another can.</i>",
   "<i>Und Innos, in seiner Weisheit, tat es.</i>",
   "<i>Oh my god, it even has random epigraphs.</i>",
][Math.floor(Math.random() * 16)];
